---
title: "Machine learning for predicting stunting - Data Wrangling"
author: "Eric Anku"
format: html
---

```{r load-packages}
pacman::p_load(
  tidyverse,
  rio,
  here,
  finalfit,
  skimr
)
```

```{r load-dataset}
df <- import(here("data", "ch.sav"))
```

```{r skim-dataset}
skim(df)
```

```{r rename-columns}
# Rename features and use descriptive names
df_clean <- df%>%
  rename(
    cluster_number_one = HH1,
    household_number_one = HH2,
    line_number = LN,
    cluster_number_two = UF1,
    household_number_two = UF2,
    child_line_number = UF3,
    interview_number = UFINT,
    mother_line_number = UF4,
    interview_number_tw0 = UF5,
    supervisor_number = UF6,
    day_interview = UF7D,
    month_interview = UF7M,
    year_interview = UF7Y,
    household_interviewer = UF9,
    consent = UF10,
    result_interview_u5 = UF17,
    start_interview_hour = UF8H,
    start_interview_minutes = UF8M,
    end_interview_hour = UF11H,
    end_interview_minutes = UF11M,
    language_questionnaire = UF12,
    language_interview = UF13,
    native_language_respondent = UF14,
    translator_used = UF15,
    household_interviewer_two = UFHINT,
    day_birth_child = UB1D,
    month_birth_child = UB1M,
    year_birth_child = UB1Y,
    age_child = UB2,
    ever_attended_child_programme = UB6,
    attended_early_education = UB7,
    currently_attended_child_programme = UB8,
    covered_health_insurance = UB9,
    health_insurance_nhis = UB10A,
    health_insurance_employer = UB10B,
    health_insurance_private = UB10D,
    health_insurance_other = UB10X,
    health_insurance_no_response = UB10NR,
    ever_registered_insurance_scheme = UB11,
    never_registerd_with_private_insurance_premium = UB12A,
    never_registered_with_private_insurance_confidence = UB12B,
    never_registered_with_private_insurance_knowledge = UB12C,
    never_registered_with_private_insurance_location = UB12D,
    never_registered_with_private_insurance_office = UB12E,
    never_registered_with_private_insurance_no_need = UB12F,
    never_registered_with_private_insurance_cover = UB12G,
    never_registered_with_private_insurance_no_money = UB12H,
    nver_registered_with_private_insurance_other = UB12X,
    never_registered_with_private_insurance_no_response = UB12NR,
    birth_certificate = BR1,
    birth_registered = BR2,
    know_register_birth = BR3,
    children_books = EC1,
    homemade_toys = EC2A,
    toys_shops = EC2B,
    household_objects = EC2C,
    days_left_alone = EC3A,
    days_left_with_another_child = EC3B,
    read_books_mother = EC5AA,
    read_books_father = EC5AB,
    read_books_other = EC5AX,
    read_books_none = EC5AY,
    read_books_no_response = EC5ANR,
    tell_stories_mother = EC5BA,
    tell_stories_father = EC5BB,
    tell_stories_other = EC5BX,
    tell_stories_no_one = EC5BY,
    tell_stories_no_reponse = EC5BNR,
    sang_songs_mother = EC5CA,
    sang_songs_father = EC5CB,
    sang_songs_other = EC5CX,
    sang_songs_no_one = EC5CY,
    sang_songs_no_response = EC5CNR,
    took_outside_mother = EC5DA,
    took_outside_father = EC5DB,
    took_outside_other = EC5DX,
    took_outside_no_one = EC5DY,
    took_response_no_response = EC5DNR,
    played_with_mother = EC5EA,
    played_with_father = EC5EB,
    played_with_other = EC5EX,
    played_with_no_one = EC5EY,
    played_with_no_response = EC5ENR,
    named_mother = EC5FA,
    named_father = EC5FB,
    named_other = EC5FX,
    named_no_one = EC5FY,
    named_no_response = EC5FNR,
    child_identifies_ten_letter = EC6,
    child_read_four_words = EC7,
    child_recognises_numbers = EC8,
    child_pick_object_two_fingers = EC9,
    child_sometimes_too_sick = EC10,
    child_follows_direction = EC11,
    child_do_independently = EC12,
    child_along_children = EC13,
    child_bites_children_adults = EC14,
    child_distracted_easily = EC15,
    took_away_privileges = UCD2A,
    explained_behaviour_wrong = UCD2B,
    shook_child = UCD2C,
    shouted_at_child = UCD2D,
    gave_child_something = UCD2E,
    spanked_child_bare_hand = UCD2F,
    hit_child_bottom = UCD2G,
    called_child_dumb = UCD2H,
    hit_child_face_head_ears = UCD2I,
    hit_child_hand_arm_leg = UCD2J,
    beat_child = UCD2K,
    believe_child_physically_punished = UCD5,
    child_wear_glasses = UCF2,
    child_hearing_aid = UCF3,
    child_assistance_walking = UCF4,
    child_difficulty_seeing = UCF7,
    child_difficulty_sounds = UCF9,
    without_equipment_child_difficult_walking = UCF11,
    when_equipment_child_difficult_walking = UCF12,
    compared_child_difficulty_walking = UCF13,
    compared_child_difficulty_picking = UCF14,
    child_difficulty_understanding_parent = UCF15,
    child_difficulty_understood_parent = UCF16,
    child_learning_things = UCF17,
    child_difficulty_playing = UCF18,
    compared_children_child_kick_other_children = UCF19,
    child_ever_breastfed = BD2,
    child_being_breastfed = BD3,
    child_nipple_yesterday = BD4,
    child_ors_yesterday = BD5,
    child_vitamins_yesterday = BD6,
    child_drank_plain_water_yesterday = BD7A,
    child_drank_tea = BD7A1,
    child_drank_juice = BD7B,
    child_drank_water_soup = BD7C,
    child_drank_infant_formula = BD7D,
    times_child_drank_infant_formula = BD7D1,
    child_drank_milk = BD7E,
    times_child_drank = BD7E1,
    child_drank_any_liquid = BD7X,
    child_drank_yogurt = BD8A,
    times_drank_yogurt = BD8A1,
    child_ate_fortified_baby_food = BD8B,
    child_ate_fortified_baby_food_weanimix = BD8B1,
    child_ate_foods_grains = BD8C,
    child_ate_pumpkin = BD8D,
    child_ate_white_potatoes = BD8E,
    child_ate_green_leafy = BD8F,
    child_ate_mangoes_pawpaw = BD8G,
    child_ate_other_fruits_vegetables = BD8H,
    child_ate_liver = BD8I,
    child_ate_meat = BD8J,
    child_ate_insects = BD8J1,
    child_ate_eggs = BD8K,
    child_fresh_dried_fish = BD8L,
    child_ate_beans = BD8M,
    child_ate_cheese = BD8N,
    child_ate_sugary_foods = BD8O,
    child_ate_food_red_palm_oil = BD8P,
    child_ate_solid_food = BD8X,
    times_child_ate_solid_food = BD9,
    dummy_bd8_explanation = BD8DUMMY,
    vaccination_card_child = IM2,
    ever_vaccination_child = IM3,
    card_document_seen = IM5,
    day_bcg_immunization = IM6BD,
    month_bcg_immunization = IM6BM,
    year_bcg_immunization = IM6BY,
    day_polio_immunization = IM6P0D,
    month_polio_immunization = IM6P0M,
    year_polio_immunization = IM6P0Y,
    day_polio1_immunization = IM6P1D,
    month_polio1_immunization= IM6P1M,
    year_polio1_immunization = IM6P1Y,
    day_polio2_immunization = IM6P2D,
    month_polio2_immunization = IM6P2M,
    year_polio2_immunization = IM6P2Y,
    day_polio3_immunization = IM6P3D,
    month_polio3_immunization = IM6P3M,
    year_polio3_immunization = IM6P3Y,
    day_pentavalent_immunization = IM6PENTA1D,
    month_pentavalent_immunization = IM6PENTA1M,
    year_pentavalent_immunization = IM6PENTA1Y,
    day_pentavalent2_immunization = IM6PENTA2D,
    month_pentavalent2_immunization = IM6PENTA2M,
    year_pentavalent2_immunization = IM6PENTA2Y,
    day_pentavalent3_immunization = IM6PENTA3D,
    month_pentavalent3_immunization = IM6PENTA3M,
    year_pentavalent3_immunization = IM6PENTA3Y,
    day_pneumococcal_immunization = IM6PCV1D,
    month_pneumococcal_immunization = IM6PCV1M,
    year_pneumococcal_immunization = IM6PCV1Y,
    day_pneumococcal2_immunization = IM6PCV2D,
    month_pneumococcal2_immunization = IM6PCV2M,
    year_pneumococcal2_immunization = IM6PCV2Y,
    day_pneumococcal3_immunization = IM6PCV3D,
    month_pneumococcal3_immunization = IM6PCV3M,
    year_pneumococcal3_immunization = IM6PCV3Y,
    day_rotation_immunization = IM6R1D,
    month_rotation_immunization = IM6R1M,
    year_rotation_immunization = IM6R1Y,
    day_rotation2_immunization = IM6R2D,
    month_rotation2_immunization = IM6R2M,
    year_rotation2_immunization = IM6R2Y,
    day_mr_immunization = IM6MD,
    month_mr_immunization = IM6MM,
    year_mr_immunization = IM6MY,
    day_yellow_fever_immunization = IM6YD,
    month_yellow_fever_immunization = IM6YM,
    year_yellow_fever_immunization = IM6YY,
    day_mr2_immunization = IM6ND,
    month_mr2_immunization = IM6NM,
    year_mr2_immunization = IM6NY,
    day_men_a_immunization = IM6OD,
    month_men_a_immunization = IM6OM,
    year_men_a_immunization = IM6OY,
    day_vitamin_a_immunization_six = IM6QD,
    month_vitamin_a_immunization_six = IM6QM,
    year_vitamin_a_immunization_six = IM6QY,
    day_vitamin_a_immunization_s12 = IM6SD,
    month_vitamin_a_immunization_s12 = IM6SM,
    year_vitamin_a_immunization_s12 = IM6SY,
    day_vitamin_a_immunization_s18 = IM6RD,
    month_vitamin_a_immunization_s18 = IM6RM,
    year_vitamin_a_immunization_s18 = IM6RY,
    participate_campaign_national_immuzation_a = IM8A,
    participate_campaign_national_immuzation_b = IM8B,
    participate_campaign_national_immuzation_c = IM8C,
    child_received_other_vaccination = IM9,
    child_ever_received_any_vaccination = IM11,
    participate_campaign_a = IM12A,
    participate_campaign_b = IM12B,
    participate_campaign_c = IM12C,
    child_given_bcg_vaccination = IM14,
    child_ever_given_polio_drops = IM16,
    polio_drops_first_two_weeks = IM17,
    times_received_polio_drops = IM18,
    child_ever_given_pentavelent_vaccination = IM20,
    times_received_pentavelent_vaccination = IM21,
    child_ever_received_pneumococcal_vaccination = IM22,
    times_received_pneumococcal_vaccination = IM23,
    child_ever_received_rotavirus = IM24,
    times_received_rotavirus = IM25,
    child_ever_given_mr1 = IM26A,
    child_ever_given_mr2 = IM26B,
    child_ever_given_yellow_fever = IM27,
    child_ever_given_men_a = IM27B,
    child_had_diarrhoea_last_two_weeks = CA1,
    child_drank_less_more_diarrhoea = CA3,
    child_ate_less_more_diarrhoea = CA4,
    sought_advice_for_diarrhoea = CA5,
    place_sought_care_govt_hospital = CA6A,
    place_sought_care_govt_health_center = CA6B,
    place_sought_care_govt_health_post = CA6C,
    place_sought_care_community_health_worker = CA6D,
    place_sought_care_mobile_outreach_clinic = CA6E,
    place_sought_care_other_public = CA6H,
    place_sought_care_private_hospital = CA6I,
    place_sought_care_private_physician = CA6J,
    place_sought_care_private_pharmacy = CA6K,
    place_sought_care_community_health_worker_non_govt = CA6L,
    place_sought_care_mobile_clinic = CA6M,
    place_sought_care_other_private_medical = CA6O,
    place_sought_care_relative_friend = CA6P,
    place_sought_care_shop_market_street = CA6Q,
    place_sought_care_traditional_practitioner = CA6R,
    place_sought_care_other = CA6X,
    place_sought_care_missing = CA6NR,
    child_given_ors_solution = CA7A,
    child_given_zinc_tablets = CA7C,
    child_given_govt_homemade_fluid = CA7D,
    child_given_coconut_water = CA7AA,
    child_given_rice_water = CA7AB,
    child_given_kenkey_water = CA7AC,
    place_got_ors_govt_hospital = CA9A,
    place_got_ors_govt_health_centre = CA9B,
    place_got_ors_govt_health_post = CA9C,
    place_got_ors_community_health_worker = CA9D,
    place_got_ors_moble_outreach_clinic = CA9E,
    place_got_ors_other_public = CA9H,
    place_got_ors_private_hospital = CA9I,
    place_got_ors_private_physician = CA9J,
    place_got_ors_private_pharmacy = CA9K,
    place_got_ors_community_health_worker_non_govt = CA9L,
    place_got_ors_mobile_clinic = CA9M,
    place_got_ors_other_private_medical = CA9O,
    place_got_ors_relative_friend = CA9P,
    place_got_ors_shop_market_street = CA9Q,
    place_got_ors_traditional_practitioner = CA9R,
    place_got_ors_other = CA9X,
    place_got_ors_dk_dont_remember = CA9Z,
    place_got_ors_missing = CA9NR,
    place_got_ors_govt_hospital_two = CA11A,
    place_got_ors_govt_health_centre_two = CA11B,
    place_got_ors_govt_health_post_two = CA11C,
    place_got_ors_community_health_worker_two = CA11D,
    place_got_ors_moble_outreach_clinic_two = CA11E,
    place_got_ors_other_public_two = CA11H,
    place_got_ors_private_hospital_two = CA11I,
    place_got_ors_private_physician_two = CA11J,
    place_got_ors_private_pharmacy_two = CA11K,
    place_got_ors_community_health_worker_non_govt_two = CA11L,
    place_got_ors_mobile_clinic_two = CA11M,
    place_got_ors_other_private_medical_two = CA11O,
    place_got_ors_relative_friend_two = CA11P,
    place_got_ors_shop_market_street_two = CA11Q,
    place_got_ors_traditional_practitioner_two = CA11R,
    place_got_ors_other_two = CA11X,
    place_got_ors_dk_dont_remember_two = CA11Z,
    place_got_ors_missing_two = CA11NR,
    anything_else_given_diarrhoea = CA12,
    other_treatment_antibiotic_pill = CA13A,
    other_treatment_antimotility = CA13B,
    other_treatment_other_pill_syrup = CA13G,
    other_treatment_unkown_pill_syrup = CA13H,
    other_treatment_antibiotic_injection = CA13L,
    other_treatment_non_antibiotic = CA13M,
    other_treament_unknown_injection = CA13N,
    other_treatment_intravenous = CA13O,
    other_treatment_home_remedy = CA13Q,
    other_treatment_other = CA13X,
    other_treatment_missing = CA13NR,
    child_ill_fever_two_weeks = CA14,
    blood_taken_finger_heel = CA15,
    child_ill_cough_two_weeks = CA16,
    difficulty_breathing_illness_cough = CA17,
    symptoms_chest_blocked_nose = CA18,
    sought_advice_treatment_illness = CA20,
    place_sought_care_govt_hospital_illness = CA21A,
    place_sought_care_govt_health_center_illness = CA21B,
    place_sought_care_govt_health_post_illness = CA21C,
    place_sought_care_community_health_worker_illness = CA21D,
    place_sought_care_mobile_outreach_clinic_illness = CA21E,
    place_sought_care_other_public_illness = CA21H,
    place_sought_care_private_hospital_illness = CA21I,
    place_sought_care_private_physician_illness = CA21J,
    place_sought_care_private_pharmacy_illness = CA21K,
    place_sought_care_community_health_worker_non_govt_illness = CA21L,
    place_sought_care_mobile_clinic_illness = CA21M,
    place_sought_care_other_private_medical_illness = CA21O,
    place_sought_care_relative_friend_illness = CA21P,
    place_sought_care_shop_market_street_illness = CA21Q,
    place_sought_care_traditional_practitioner_illness = CA21R,
    place_sought_care_other_illness = CA21X,
    place_sought_care_missing_illness = CA21NR,
    given_medicine_treat_illness = CA22,
    medicine_act = CA23A,
    medicine_dhp = CA23C,
    medicine_aa = CA23E,
    medicine_al = CA23G,
    medicine_herbal_medicine = CA23H,
    medicine_other_antimalarial = CA23K,
    medicine_antibiotics_amoxicillin = CA23L,
    medicine_antibiotics_cotrimoxadole = CA23M,
    medicine_antibiotics_other_pill_syrup = CA23N,
    medicine_antibiotics_other_injection = CA23O,
    medicine_para_panadol_acetaminophen = CA23R,
    medicine_aspirin = CA23S,
    medicine_ibuprofen = CA23T,
    medicine_other = CA23X,
    medicine_dk = CA23Z,
    medicine_missing = CA23NR,
    place_got_antibiotics_govt_hospital = CA25A,
    place_got_antibiotics_govt_health_centre = CA25B,
    place_got_antibiotics_govt_health_post = CA25C,
    place_got_antibiotics_community_health_worker = CA25D,
    place_got_antibiotics_moble_outreach_clinic = CA25E,
    place_got_antibiotics_other_public = CA25H,
    place_got_antibiotics_private_hospital = CA25I,
    place_got_antibiotics_private_physician = CA25J,
    place_got_antibiotics_private_pharmacy = CA25K,
    place_got_antibiotics_community_health_worker_non_govt = CA25L,
    place_got_antibiotics_mobile_clinic = CA25M,
    place_got_antibiotics_other_private_medical = CA25O,
    place_got_antibiotics_relative_friend = CA25P,
    place_got_antibiotics_shop_market_street = CA25Q,
    place_got_antibiotics_traditional_practitioner = CA25R,
    place_got_antibiotics_other = CA25X,
    place_got_antibiotics_dk_dont_remember = CA25Z,
    place_got_antibiotics_missing = CA25NR,
    place_got_antimalaria_govt_hospital = CA27A,
    place_got_antimalaria_govt_health_centre = CA27B,
    place_got_antimalaria_govt_health_post = CA27C,
    place_got_antimalaria_community_health_worker = CA27D,
    place_got_antimalaria_moble_outreach_clinic = CA27E,
    place_got_antimalaria_other_public = CA27H,
    place_got_antimalaria_private_hospital = CA27I,
    place_got_antimalaria_private_physician = CA27J,
    place_got_antimalaria_private_pharmacy = CA27K,
    place_got_antimalaria_community_health_worker_non_govt = CA27L,
    place_got_antimalaria_mobile_clinic = CA27M,
    place_got_antimalaria_other_private_medical = CA27O,
    place_got_antimalaria_relative_friend = CA27P,
    place_got_antimalaria_shop_market_street = CA27Q,
    place_got_antimalaria_traditional_practitioner = CA27R,
    place_got_antimalaria_other = CA27X,
    place_got_antimalaria_dk_dont_remember = CA27Z,
    place_got_antimalaria_missing = CA27NR,
    got_medicine_after_fever = CA29,
    method_dispose_stools = CA31,
    cluster_number_three = AN1,
    household_number_three = AN2,
    child_line_number_two = AN3,
    age_child_two = AN4,
    mother_line_number_two = AN5,
    interviewer_number = AN6,
    measurer_id_code = AN7,
    child_weight_kg = AN8,
    child_undressed_minimum = AN9,
    child_lenhei_cm = AN11,
    child_measure_lenhei = AN12,
    day_measurement_anthro = AN13D,
    month_measurement_anthro = AN13M,
    year_measurement_anthro = AN13Y,
    supervisor_number_two = HH4,
    area = HH6,
    region = HH7,
    sex = HL4,
    highest_level_education = ED5A,
    highest_grade_attended = ED5B,
    date_interview_child = CDOI,
    date_birth_child = CDOB,
    age_months = CAGE,
    age_months_6 = CAGE_6,
    age_months_11 = CAGE_11,
    age_days = CAGED,
    hfa_percentile_nchs = HAP,
    hfa_z_score_nchs = HAZ,
    hfa_reference_median_nchs = HAM,
    wfa_percentile_nchs = WAP,
    wfa_z_score_nchs = WAZ,
    wfa_reference_median_nchs = WAM,
    wfh_percentile_nchs = WHP,
    wfh_z_score_nchs = WHZ,
    wfh_reference_median_nchs = WHM,
    flag_indicators = FLAG,
    bmi_who = BMI,
    bmi_z_score_who = ZBMI,
    hfa_z_score_who = HAZ2,
    wfa_z_score_who = WAZ2,
    wfh_z_score_who = WHZ2,
    hfa_flag_who = HAZFLAG,
    wfa_flag_who = WAZFLAG,
    whz_flag_who = WHZFLAG,
    bmi_flag_who = BMIFLAG,
    whz_age_flag_who = WHZNOAGE,
    stratum = stratum,
    mother_educational_level = melevel,
    health_insurance = cinsurance,
    functional_disability_two_four_years = cdisability,
    mother_functional_disability_18_49 = caretakerdis,
    ethnicity = ethnicity,
    number_women_20_24 = OVERSAMPLED,
    listing_category = LIST_CAT,
    child_under_five_sample_weight = chweight,
    combined_wealth_score = wscore,
    wealth_index_quintile = windex5,
    wealth_index_decile = windex10,
    urban_wealth_score = wscoreu,
    urban_wealth_index_quintile = windex5u,
    urban_wealth_index_decile = windex10u,
    rural_wealth_score = wscorer,
    rural_wealth_index_quintile = windex5r,
    rural_wealth_index_decile = windex10r,
    primary_sampling_unit = PSU
  )
```

```{r skim-clean-data}
skim(df_clean)
```

```{r drop-columns-fifty-percent}
threshold <- 0.5 # Set the threshold for missing values

# Calculate the percentage of missing values for each column
missing_percent <- colMeans(is.na(df))

# Get the names of columns with missing values exceeding the threshold
cols_to_drop <- names(missing_percent[missing_percent > threshold])

# Drop the columns from the data frame
df_clean <- df[, !(names(df) %in% cols_to_drop)]
```

